# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'My.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet(
            'border-style: outset;'
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0,"
            "stop:0 rgba(0,191,255, 200), stop:1 rgba(224,255,255, 210));")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 500, 400))
        self.groupBox.setObjectName("groupBox")
        self.groupBox.setStyleSheet(
            'background-image:url(E:\yolov5\yuyin\hit.jpg)'
            'border-style: outset;'
            'border-radius: 40px;'
            'border: 2px groove gray;'
        )
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(70,190,150,60))
        self.pushButton.setObjectName("start")
        self.pushButton.setStyleSheet(
            'background-color: rgb(255,255,255);'
            'border-radius: 20px;'
            'border: 2px groove gray;'
            'border-style: outset;'
            'font-size:20px;color:rgb(0,0,205)')
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(70,285,150,60))
        self.pushButton_2.setObjectName("end")
        self.pushButton_2.setStyleSheet(
            'background-color: rgb(255,255,255);'
            'border-radius: 20px;'
            'border: 2px groove gray;'
            'border-style: outset;'
            'font-size:20px;color:rgb(0,0,205)')
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(45,50,200,100))
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setStyleSheet(
            'background-color: rgb(255,255,255);'
            'border-radius: 40px;'
            'border: 2px groove gray;'
            'border-style: outset;'
            'font-size:20px;color:rgb(0,0,205)')
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(265, 50, 200, 100))
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet(
            'background-color: rgb(255,255,255);'
            'border-radius: 40px;'
            'border: 2px groove gray;'
            'border-style: outset;'
            'font-size:20px;color:rgb(0,0,205)')
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 245, 150, 60))
        self.pushButton_3.setStyleSheet(
            'background-color: rgb(255,255,255);'
            'border-radius: 20px;'
            ' border: 2px groove gray;'
            'border-style: outset;'
            'font-size:20px;color:rgb(0,0,205)')
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", ""))
        self.pushButton.setText(_translate("MainWindow", "起始仓库"))
        self.pushButton_2.setText(_translate("MainWindow", "目标仓库"))
        self.label.setText(_translate("MainWindow", "搬运控制命令"))
        self.label_2.setText(_translate("MainWindow", "简单控制命令"))
        self.pushButton_3.setText(_translate("MainWindow", "初始化/录入"))
